name: Docker Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [8.3-fpm, 8.3-fpm-alpine, 8.4-fpm, 8.4-fpm-alpine, 8.5-fpm]
        arch: [amd64, arm64]

    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Arch-specific image
        run: |
          cd ${{ matrix.version }}
          docker build -t brighterly/php:${{ matrix.version }}-${{ matrix.arch }} .
          docker push brighterly/php:${{ matrix.version }}-${{ matrix.arch }}

  create-manifest:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [8.3-fpm, 8.3-fpm-alpine, 8.4-fpm, 8.4-fpm-alpine, 8.5-fpm]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and Push Manifest
        run: |
          docker manifest create brighterly/php:${{ matrix.version }} \
            --amend brighterly/php:${{ matrix.version }}-amd64 \
            --amend brighterly/php:${{ matrix.version }}-arm64
          docker manifest push brighterly/php:${{ matrix.version }}
